package models

import (
	"encoding/json"
	"fmt"
	"html/template"
	"simulation-client/logging"
)

// This contains a record, generated by the server, of the results of the actions
type Trace struct {
	Id            int `json:"id"`
	Simulation_id int `json:"simulation_id"`
	TimeStamp     int
	UserName      string `json:"username"`
	Level         int    `json:"level"`
	Message       string `json:"message"`
	SafeHtml      template.HTML
}

// Wrapper for the TraceList. No need to distinguish between viewed and compared
// fields for the trace table, so we have a separate template loader method.
func Traces(u *User) *[]template.HTML {
	table := u.GetCurrentSimulation().Trace
	t := table.Table.(*[]Trace)
	l := len(*t)
	htmlTable := make([]template.HTML, l)

	for i := range *t {
		var nextLevel int
		item := (*t)[i]
		if i < l-1 {
			nextItem := (*t)[i+1]
			nextLevel = nextItem.Level
		} else {
			nextLevel = item.Level
		}
		htmlTable[i] = item.ShowTrace(nextLevel)
	}

	return &htmlTable
}

// Create a safe HTML representation for one line of the trace page
// Facilitate nested accordion using the 'beefup' implementation
// Could be adapted to more or less any nested accordion implementation
// The idea is
// (1) when trace goes down one level, clicking on the line above hides the lower level
// (2) a toggle button at the top folds all items below a defined level
//
//		t: a single element of the Trace array
//		nextLevel: the level of the element immediately following t
//	 returns: a safe HTML string representing t
func (t Trace) ShowTrace(nextLevel int) template.HTML {
	var htmlString string

	// I used the next two lines to diagnose Trace errors. Can probably be junked
	// diagnostic := strconv.Itoa(t.Level) + `:`
	// htmlContent:= diagnostic + t.Message

	htmlContent := t.Message

	subItemString := fmt.Sprintf(`<article data-accordion><button data-control level_%d>%s</button><div data-content>`, t.Level, htmlContent)
	continueString := fmt.Sprintf(`<article level_%d> %s </article>`, t.Level, htmlContent)
	endString := fmt.Sprintf(`<article level_%d> %s </article></div></article>`, t.Level, htmlContent)

	// Start subitem
	if nextLevel > t.Level {
		// Report an error if the API supplies a trace with an unterminated subitem
		if nextLevel-t.Level > 1 {
			logging.TraceErrorf("Unterminated subitem %s received from API with level=%d and nextLevel=%d", t.Message, t.Level, nextLevel)
		}
		htmlString = subItemString
	}

	// Continue subitem
	if nextLevel == t.Level {
		htmlString = continueString
	}

	// Terminate subitem and start a new item at the level above
	// This has to be terminated externally with a final </article></div>
	if nextLevel < t.Level {
		htmlString = endString
	}
	return template.HTML(htmlString)
}

// Custom MarshalJSON to suppress printout of Trace Records
// TODO suppress entire Trace table (which is a map, so I haven't yet found out how to do this)
// TODO I think it involves checking the actual name of the key but then avoiding infinite recursion
func (i Trace) MarshalJSON() ([]byte, error) {
	return json.Marshal(&struct {
		Tldr string `json:"tldr"`
	}{
		Tldr: "Trace record suppressed",
	})
}
